# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c90d7fa016749fb67cec749f8047f033d011519869002048f8339f345661cd548941c5e13d1c1c112d6d98762eb048eb5fd1358836e0cb4fd43160e52c215339

test:
  secret_key_base: 4d0d0876ef9d94fe96e04927d14d83e13c5ce858d23bbfd097951cf0f4b2edbb2df06fe98fba0733af4ecb84f6ea21eb00dfe4337d1792ed0e2cdcf285926a23

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
